/**
 * Pulls the webfonts local. Run with `npm run fetch:fonts`.
 *
 * The site used to link Google's stylesheet, which fetches the CSS from one
 * Google host and the font files from another. Two problems with that, and the
 * smaller one is speed.
 *
 * The larger one is that a `<link>` in the head fires on first paint, before a
 * consent banner has rendered — so a German visitor's IP address reaches
 * Google before they have been asked anything. A Munich court awarded damages
 * over exactly that in 2022. A banner cannot govern a request that has already
 * happened; hosting the files here is the only version of this that works.
 *
 * The speed part: Google's CSS has to be fetched and parsed before the browser
 * learns which font files it needs, so the fonts are two round trips deep on
 * the critical path, across two extra DNS and TLS handshakes. From here they
 * are same-origin on a connection that is already open, and the two faces the
 * first screen needs are preloaded in `index.html`.
 *
 * The declarations are Google's own, verbatim apart from the URLs — same
 * weights, same unicode-ranges, same `font-display: swap` — so nothing about
 * the rendering changes. Only the subsets this site can render are kept.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

/** Everything the site's copy is written in. Cyrillic, Greek and Vietnamese
    are the other 19 faces Google offers for these families, and no page here
    can render a character from any of them. */
const SUBSETS = ['latin', 'latin-ext'];

/*
 * Weight ranges, not a list of weights — these three are variable fonts, and
 * asking for a range gets one file that carries all of it.
 *
 * The site asked for named weights, so Google cut a static instance per
 * weight: three files for Bricolage and four for Montserrat, each the size of
 * the variable font that replaces all of them. Measured, latin only:
 *
 *   Bricolage   225KB as 400/700/800  ->  75KB as one file covering 400-800
 *   Montserrat  148KB as 400/500/600/700 -> 37KB covering 400-700
 *
 * Playfair is one weight and its italic, so it is the same either way.
 */
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Bricolage+Grotesque:opsz,wght@12..96,400..800' +
  '&family=Montserrat:wght@400..700' +
  '&family=Playfair+Display:ital,wght@0,400;1,400' +
  '&display=swap';

/* Google serves woff2 only to browsers it recognises. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36';

const OUT_DIR = 'public/fonts';
const CSS_OUT = 'src/styles/fonts.css';

const slug = (family) =>
  family
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
const kb = (n) => (n / 1024).toFixed(1) + 'KB';

const source = process.argv[2]
  ? await readFile(process.argv[2], 'utf8')
  : await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

/* Each face in Google's CSS is preceded by a comment naming its subset. */
const blocks = [
  ...source.matchAll(/\/\* (?<subset>[a-z-]+) \*\/\s*@font-face \{(?<body>[^}]+)\}/g),
];
if (!blocks.length) throw new Error('No @font-face blocks found — did the request return HTML?');

const field = (body, name) => new RegExp(`${name}:\\s*([^;]+);`).exec(body)?.[1].trim();

const kept = [];
let downloaded = 0;

await mkdir(OUT_DIR, { recursive: true });

for (const { groups } of blocks) {
  const { subset, body } = groups;
  if (!SUBSETS.includes(subset)) continue;

  const family = field(body, 'font-family').replace(/['"]/g, '');
  const style = field(body, 'font-style');
  const weight = field(body, 'font-weight');
  const url = /url\(([^)]+)\)/.exec(body)[1];

  const range = weight.includes(' ') ? weight.replace(/ /g, '-') : weight;
  const name = `${slug(family)}-${range}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
  const file = path.join(OUT_DIR, name);

  const response = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!response.ok) throw new Error(`${response.status} fetching ${url}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  await writeFile(file, bytes);
  downloaded += bytes.length;

  kept.push({
    family,
    style,
    weight,
    subset,
    name,
    size: bytes.length,
    stretch: field(body, 'font-stretch'),
    range: field(body, 'unicode-range'),
  });

  console.log(`  ✓ ${name}  ${kb(bytes.length)}`);
}

const css =
  `/*\n` +
  ` * The site's typefaces, served from this origin.\n` +
  ` *\n` +
  ` * Generated by \`npm run fetch:fonts\` — edit that script, not this file.\n` +
  ` * The declarations are Google's own: same weights, same unicode-ranges, same\n` +
  ` * swap behaviour. Only latin and latin-ext are kept; the families also offer\n` +
  ` * Cyrillic, Greek and Vietnamese, and no page here can render them.\n` +
  ` *\n` +
  ` * Why these are not fetched from Google any more: see the script's header.\n` +
  ` */\n\n` +
  kept
    .map(({ family, style, weight, stretch, name, range, subset }) =>
      [
        `/* ${family} ${weight}${style === 'italic' ? ' italic' : ''} — ${subset} */`,
        `@font-face {`,
        `  font-family: '${family}';`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        stretch ? `  font-stretch: ${stretch};` : null,
        `  font-display: swap;`,
        `  src: url('/fonts/${name}') format('woff2');`,
        `  unicode-range: ${range};`,
        `}`,
      ]
        .filter(Boolean)
        .join('\n'),
    )
    .join('\n\n') +
  '\n';

await writeFile(CSS_OUT, css);

console.log(`\n${kept.length} faces, ${kb(downloaded)} total -> ${OUT_DIR}`);
console.log(`Declarations written to ${CSS_OUT}`);
