/**
 * Writes `sitemap.xml` and the `Sitemap:` line in `robots.txt` from the list
 * of pages the build actually prerendered.
 *
 * It used to be a hand-written file in `public/`. It was correct — 46 URLs,
 * every one of them real — and it was correct the way a second list is always
 * correct right up until it is not. `react-router.config.js` already holds the
 * list of what gets built, and the job adverts and blog posts are generated
 * from the copy deck, so adding a post meant remembering to add it here too.
 * The one that goes stale is always the one nobody looks at, and their live
 * site is the proof: 12 posts published, 9 in the sitemap, and not one of them
 * the same 9.
 *
 * It also hardcoded `https://ecomsniper.io`, so a preview deploy published a
 * sitemap pointing at somebody else's site — the same fault the canonicals had.
 * The origin comes from `VITE_SITE_ORIGIN`, exactly as it does there.
 *
 * ## What is left out, and why
 *
 * - `/404` and `/de/404` are documents the host serves under a 404 status,
 *   not pages anyone links to.
 * - `/login`, `/register` and their German pair are `noindex`, and
 *   `robots.txt` disallows them. Listing a page you have asked not to be
 *   indexed is a contradiction a search console reports back at you.
 *
 * ## No `lastmod`, deliberately
 *
 * A wrong `lastmod` is worse than none: it teaches a crawler to distrust the
 * whole file. The honest source would be the last commit that touched each
 * page, and Netlify clones shallow, so that date is not reliably available at
 * build time. Their sitemap has none either, and it is not what is wrong with
 * it. `priority` is gone for a simpler reason: Google ignores it.
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ORIGIN = (process.env.VITE_SITE_ORIGIN || 'https://ecomsniper.io').replace(/\/+$/, '');
const OUT = 'build/client';

const config = await import('../react-router.config.js');
const prerendered = config.default.prerender;

/** Pages that exist but must not be listed. See the header. */
const EXCLUDED = new Set(['/404', '/de/404', '/login', '/register', '/de/login', '/de/register']);

const paths = prerendered.filter((path) => !EXCLUDED.has(path));

/** The same page without its language prefix. "/de" is the German homepage. */
const stripLanguage = (path) => {
  if (path === '/de') return '/';
  return path.startsWith('/de/') ? path.slice(3) : path;
};

const germanFor = (englishPath) => (englishPath === '/' ? '/de' : `/de${englishPath}`);

/* One <url> per address, English first, each listing every alternate
   including itself — which is what the spec asks for and what makes the pair
   read as one page in two languages rather than two pages competing. */
const english = paths.filter((path) => stripLanguage(path) === path);

const url = (path) => `${ORIGIN}${path === '/' ? '/' : path}`;

const entries = [];
for (const path of english) {
  const german = germanFor(path);
  const hasGerman = paths.includes(german);

  for (const variant of hasGerman ? [path, german] : [path]) {
    const alternates = [`    <xhtml:link rel="alternate" hreflang="en" href="${url(path)}" />`];
    if (hasGerman) {
      alternates.push(`    <xhtml:link rel="alternate" hreflang="de" href="${url(german)}" />`);
    }
    alternates.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${url(path)}" />`);

    entries.push(`  <url>\n    <loc>${url(variant)}</loc>\n${alternates.join('\n')}\n  </url>`);
  }
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/generate-sitemap.mjs from the prerender list in
  react-router.config.js. Do not edit: the next build overwrites it.

  The xhtml:link alternates tell a search engine these are the same page in two
  languages rather than two pages competing for the same terms. Each URL lists
  every alternate including itself.
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${entries.join('\n')}
</urlset>
`;

writeFileSync(join(OUT, 'sitemap.xml'), xml);

/* robots.txt points at the sitemap, so it has the same problem and takes the
   same fix. Rewritten in the build output only — `public/robots.txt` stays the
   readable source. */
const robotsPath = join(OUT, 'robots.txt');
if (existsSync(robotsPath)) {
  const robots = readFileSync(robotsPath, 'utf8').replace(
    /^Sitemap:.*$/m,
    `Sitemap: ${ORIGIN}/sitemap.xml`,
  );
  writeFileSync(robotsPath, robots);
}

console.log(`sitemap: ${entries.length} URLs at ${ORIGIN}`);
